version: '2'

services:
  elasticsearch:
    image: nshou/elasticsearch-kibana:latest
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "5601:5601"
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"

